name: Test uploading and downloading artifacts
on:
  push:
    paths:
      - .github/workflows/artifact-test.yml
  workflow_dispatch:
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "this is the contents of artifacts file called app.txt" > app.txt 
      - uses: actions/upload-artifact@v4 
        with: 
          name: build-file 
          path: app.txt
  
  deploy: 
    runs-on: ubuntu-latest 
    needs: build 
    steps: 
      - uses: actions/download-artifact@v4 
        with: 
          name: build-file 
      - run: cat app.txt 